### ISSUE TITLE
Make qv files work on another pc (not the same which was made )

### ISSUE THREAD

**Issue by Iam-Muslim** [rebinf/QuranVideoMaker#26]
Alslam alikom,

to transfer a qv file to another pc it needs some modification in setting
opening a qv in another pc gives an error that mp3 file not found 
if this was bypassed by removing the mp3 from project , the project exporting is stuck at the end

**Comment by rebinf** [comment]
The QV files store absolute file paths, I've seen the same behavior in other apps.
So if you are referencing a file in `C:\Users\YourName\Videos\file.jpeg` it will be looking for the file in the same directory on another PC, so if you have a different user name, then it won't be able to find the file.
So best to store your project files in a directory like `C:\MyProject`, so that you are going to put the files in the same directory on every machine.
