### ISSUE TITLE
What is the best way to export if I have nvidia gpu

### ISSUE THREAD

**Issue by Farfighters** [rebinf/QuranVideoMaker#51]
I have a very good NVIDIA GPU and it helps in exporting in other softwares. Like I told you earlier, unfortunately I'm not too savvy  when it comes to these things. What option when exporting would you recommend to use that makes use of GPU more than CPU (right now it uses 98% CPU and makes laptop very slow, but I know that it can do better). Currently in hardware acceleration I just use auto, same with encoding speed I just use medium. What settings would you recommend for higher end GPUs to speed up exporting and make use of GPU more but still have best quality? When I looked online I didn't really understand what it was saying. Again, I know you are very busy with much more important issues, I just wanted to know with existing options what I can optimise inshallah. Jazakhallah khair again brother as always!

**Comment by rebinf** [comment]
QVM expor works in two phases:
First is the image processing and generation which uses CPU (I will look into this to see if we can have the option to use the GPU instead).
Second is "feeding" the images and everything to `ffmpeg` to produce the video, the options that you see in the export window are mostly for that.
If you open up task manager, you should see a spike in the GPU usage after all frames are rendered (that's the second phase).
`Auto` option should be fine, or you could try out different options, please know that I think depending on your hardware configuration not all options work.

Anyway, I think the problem is the first part of the process, I've created #53 to track it.
