### ISSUE TITLE
Fix EXPORT memory issues

### ISSUE THREAD

**Issue by rebinf** [rebinf/QuranVideoMaker#57]
QVM uses large amounts of memory when exporting.

**Comment by Farfighters** [comment]
Sorry for continuing in the other issue, I forgot about making new issues...

**Comment by rebinf** [comment]
> Sorry for continuing in the other issue, I forgot about making new issues...

No worries, it's just easier to track the current issues.

**Comment by Farfighters** [comment]
Assalamualaikum wbt brother, any updates on this issue? This is the main problem why I can't use QVM right now unfortunately

**Comment by Farfighters** [comment]
I know you are busy, just wanted to know approximately how long it might take inshallah

**Comment by Farfighters** [comment]
I know this is related to the memory issue, but maybe the other errors might help as well (most recent attempt at exporting):
![image](https://github.com/user-attachments/assets/c7cc17df-9747-4f84-a233-41a5afbe5aa4)

**Comment by rebinf** [comment]
wa alaykum salam, I'll try to resolve this issue very soon inshaAllah.

**Comment by Farfighters** [comment]
Assalamualaikum brother. I just wanted to ask whether you had to reduce quality of export to solve memory issues? As now when I exported and put into my other video editor, it detected as 1080p rather than 4K even when I set it as 4K. Also, looking at the videos, they look slightly worse quality than before at same settings. If this isn't related to memory then please set it as separate issue, but I was thinking it might be related to changes in export.

**Comment by rebinf** [comment]
Moved to #68
